### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by paul-phan**
Update all the dependencies to the latest version and worked perfectly.

### CODE REVIEW

**Comment by welkie** [comment]
I suggest reaching out to @Dependabot to see if they'd be willing to provide free services for this repo. They monitor outdated dependencies and provide automatic pull requests with the updates.

**Comment by havenchyk** [comment]
@welkie why not https://greenkeeper.io ?

**Comment by orta** [comment]
I'm going to close this PR - I've merged a lot of smaller dependency updates just now which don't necessarily come to this PR but it's enough that someone can built off them instead. It's been a year and also adds a yarn lockfile. Open to fresh versions of this PR though!. 

Thanks for the time!

Re: Dependabot, personally I've found them to be too noisy. I'm much more a fan of offering more people commit access if they've shown to care a lot. I don't know if this is something Microsoft does, but I'll ask around what we do WRT external contributors for certain repos.

**Comment by havenchyk** [comment]
@ora you can configure dependabot to create PRs not immediately, but after some time or major version, but personally it’s nice and secure to have deps up to date

**Pull request closed without merging**
