### PR TITLE
Fix #305 Update packages to latest

### LINKED ISSUE #305: Upgrade to TS 4.0
4.0 is released, can we move to that - maybe some refactoring?

### PR DESCRIPTION
**Pull request by samal-rasmussen**
Fix #305

* Had to add/modify a lot of types.
* I had to use a specific github commit for the connect-mongo dependency because of this: https://github.com/jdesboeufs/connect-mongo/issues/373
* Added express-session-types.d.ts in order to get returnTo on SessionData

### CODE REVIEW

**Review by peterblazejewicz — APPROVED** [review]
LGTM! tested locally (win10)
@samal-rasmussen thx!

**Comment by peterblazejewicz** [comment]
@samal-rasmussen can you force push changes? I cannot see came CI error locally (build/linter/tests)

**Comment by samal-rasmussen** [comment]
The original travis ci build errors were caused by node-sass, which is deprecated so I went ahead and changed over to the sass package and that seems to have worked for that issue.

But now the build is failing on optional catch bindings in the new versions of the dependencies. This was introduces in node 10 and the travis build is using 8 and 9. So this pr is stranded until someone updates the ci build.

**Comment by peterblazejewicz** [comment]
@samal-rasmussen i've changed the versions to be LTSs. Still, you need to take latest (rebase) and push changes with updated `.yml`, thx!

**Comment by samal-rasmussen** [comment]
Oh that's how Travis works. Had I known it was that easy :)

**Pull request merged**
