### PR TITLE
Update dependencies added airbnb style guide

### PR DESCRIPTION
**Pull request by shashankgpt**

### CODE REVIEW

**Comment by orta** [comment]
Hi @shashankgpt - I don't think we want to be too prescriptive about a style-guide in this starter repo. I'm open to having a dependency update PR separate from this though?

**Comment by shashankgpt** [comment]
Thanks Orta for reply,
Agreed. I can create a pull request for updated dependencies only. 
Regards, 
Shashank gupta

**Comment by shashankgpt** [comment]
Done!! @orta

**Comment by orta** [comment]
There's a lot of merge conflicts, is it possible you've not updated to master?

**Comment by orta** [comment]
Actually, looks like https://github.com/microsoft/TypeScript-Node-Starter/pull/200 is pretty well set up for doing the update. Let's save on duplication and merge that as it looks good right no. Thanks for contributing @shashankgpt

**Comment by shashankgpt** [comment]
Cool

**Pull request closed without merging**
