### PR TITLE
Upgrade to Bootstrap 4

### PR DESCRIPTION
**Pull request by amodolo**
- Updated dependencies version
- Upgrade bootstrap from version 3.3.7 to 4.1.2
- Adequate the views to the bootstrap changes

### CODE REVIEW

**Comment by peterblazejewicz** [comment]
@amodolo 
Can you remove all commits/changes not related to Bootstrap bump? (pckg deps updates, lock file udpates should not be in the PR, the markup rewrite, assets update are welcome). So only related changes are left in the PR
Thanks!

**Comment by peterblazejewicz** [comment]
@amodolo 
Sahat (@sahat) from the upstream project used in this one has just updated the content to the BS4. Can you compared details and make some minor changes? That would allow to ship the same L&F as in upstream project. Here is the current version link:
https://hackathon-starter-2018.herokuapp.com/
I've setup your PR locally, so I could help with stuff.

**Comment by peterblazejewicz** [comment]
And here are some remarks after updating to BS4:
https://github.com/sahat/hackathon-starter/issues/853

**Comment by imcoddy** [comment]
When can we get this conflict solved and merged into master?

**Comment by amodolo** [comment]
Sorry for the delay. I've just removed the unrelated commits

**Comment by amodolo** [comment]
I've sync the fork with the origin but i'm still having some problems with the CI. It's seams the same issue as #154

**Comment by orta** [comment]
Alright, I've got this PR built and running locally and tested it out. Looks 👍 - I've clicked around and verified that all the pieces look right and feel good. Thanks for taking the time @amodolo and @peterblazejewicz 

image

**Pull request merged**
