### PR TITLE
feat(*): update several dependencies

### PR DESCRIPTION
**Pull request by alan-agius4**
- updated several dependencies
- changed `require` to `import` in `server.ts`
- updated tests

### CODE REVIEW

**Comment by bowdenk7** [comment]
hey sorry for the long absence... I'm back now and going to spend a bunch of time refreshing this repo and I'd love to take these changes. Any chance you'd be willing to sign the CLA?

**Comment by alan-agius4** [comment]
Absolutely, link please :)?

**Comment by bowdenk7** [comment]
https://cla.opensource.microsoft.com/Microsoft/TypeScript-Node-Starter?pullRequest=53

Thanks!!

**Comment by alan-agius4** [comment]
CLA, Should be good now, can you check please?

**Comment by alan-agius4** [comment]
Thanks, CLA signed.

**Comment by bowdenk7** [comment]
Thanks!!! This is a huge help :)

**Comment by alan-agius4** [comment]
Glad to help :)

**Pull request merged**
